server:
  port: 8083
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: tg-chats-collector

tg-collector:
  telegram:
    client:
      api-id: ${TG_CLIENT_API_ID}
      api-hash: ${TG_CLIENT_API_HASH}
      phone: ${TG_CLIENT_PHONE}
  chat-loader:
    default-messages-limit: 2000
    default-days-before-limit: 60

logging:
  config: classpath:ru/panyukovnn/referenceloggingstarter/logback-spring.xml
  log-exec-time: true
  web-logging:
    log-body: true
    log-feign-requests: true
