
tg-collector:
  telegram:
    client:
      api-id: ${TG_CLIENT_API_ID}
      api-hash: ${TG_CLIENT_API_HASH}
      phone: ${TG_CLIENT_PHONE}
  chat-loader:
    default-messages-limit: 2000
    default-days-before-limit: 60
    date-range-messages-limit: 1000

quarkus:
  console:
    enabled: false # Для освобождения System.in при вводе одноразового пароля телеграм
  application:
    name: tg-chats-collector
  http:
    port: 8083
    root-path: /${quarkus.application.name}
  banner:
    enabled: false
  config:
    locations: ./application-prod.properties
  log:
    level: INFO
    console:
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n"
  package:
    jar:
      type: uber-jar
