name: Build

on:
  push:
    tags:
      - '**'

jobs:
  get-repo-name:
    # Проверка, что на коммит установлен тег и успешно прошли тесты
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.get-name.outputs.repo }}
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - id: get-name
        run: echo "repo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_OUTPUT
      - id: get-tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REF: ${{ github.event.workflow_run.ref }}

  tests:
    uses: ./.github/workflows/reusable-tests.yaml
    secrets:
      GH_PACKAGES_READ_TOKEN: ${{ secrets.GH_PACKAGES_READ_TOKEN }}
      NOTIFICATION_TELEGRAM_BOT_TOKEN: ${{ secrets.NOTIFICATION_TELEGRAM_BOT_TOKEN }}
      NOTIFICATION_TELEGRAM_CHAT_ID: ${{ secrets.NOTIFICATION_TELEGRAM_CHAT_ID }}

  build-and-push:
    needs: [ get-repo-name, tests ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.ref }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --build-arg GH_TOKEN=${{ secrets.GH_PACKAGES_READ_TOKEN }} -t ghcr.io/$GITHUB_REPOSITORY:${{ github.ref_name }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/$GITHUB_REPOSITORY:${{ github.ref_name }}

      - name: Notify Telegram on success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.NOTIFICATION_TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.NOTIFICATION_TELEGRAM_CHAT_ID }} \
            -d text="✅ ${{ needs.get-repo-name.outputs.repo }} %0A Успешно выполнена сборка тега ${{ github.ref_name }}"

      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.NOTIFICATION_TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.NOTIFICATION_TELEGRAM_CHAT_ID }} \
            -d text="❌ ${{ needs.get-repo-name.outputs.repo }} %0A Ошибка при сборке тега ${{ github.ref_name }} %0A Посмотреть лог: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
