name: Stop

on:
  workflow_dispatch:

jobs:
  get-repo-name:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.get-name.outputs.repo }}
    steps:
      - id: get-name
        run: echo "repo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_OUTPUT

  stop:
    needs: get-repo-name
    runs-on: ubuntu-latest
    steps:
      - name: Stop on server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          REMOTE_DIR: ${{ needs.get-repo-name.outputs.repo }}
          GH_TOKEN: ${{ secrets.GH_PACKAGES_READ_TOKEN }}
        run: |
          # Подключаемся к серверу и выполняем скрипт
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${SSH_USER}@${SERVER_IP} "
            cd $REMOTE_DIR
            docker compose down -v
          "

      - name: Notify Telegram on success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.NOTIFICATION_TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.NOTIFICATION_TELEGRAM_CHAT_ID }} \
            -d text="✅ ${{ needs.get-repo-name.outputs.repo }} %0A Успешно остановлен ${{ github.event.inputs.image_tag }}"

      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.NOTIFICATION_TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.NOTIFICATION_TELEGRAM_CHAT_ID }} \
            -d text="❌ ${{ needs.get-repo-name.outputs.repo }} %0A Ошибка при остановке ${{ github.event.inputs.image_tag }} %0A Посмотреть лог: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
